{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.config.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.fullname" . }}-config
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
  {{- with .Values.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.config.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
  {{- end }}
  {{- if .Values.persistence.config.volumeName }}
  volumeName: {{ .Values.persistence.config.volumeName }}
  {{- end }}
---
{{- end }}
{{- if not .Values.persistence.work.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "adguard-home.fullname" . }}-work
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
  {{- with .Values.persistence.work.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.work.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.work.size }}
  {{- if .Values.persistence.work.storageClass }}
  storageClassName: {{ .Values.persistence.work.storageClass }}
  {{- end }}
  {{- if .Values.persistence.work.volumeName }}
  volumeName: {{ .Values.persistence.work.volumeName }}
  {{- end }}
---
{{- end }}
{{- end }}
