version: '3'

vars:
  CHART_DIR: charts/adguard-home
  RELEASE_NAME: adguard-home-test

tasks:
  default:
    cmds:
      - task --list
    silent: true

  lint:
    desc: Lint the Helm chart for issues
    cmds:
      - helm lint {{.CHART_DIR}}

  test:
    desc: Run the comprehensive test suite
    cmds:
      - ./{{.CHART_DIR}}/tests/test.sh

  template:
    desc: Render chart templates with default values
    cmds:
      - helm template {{.RELEASE_NAME}} {{.CHART_DIR}}

  package:
    desc: Package the Helm chart
    cmds:
      - helm package {{.CHART_DIR}}

  install:
    desc: Install the chart in the current Kubernetes cluster
    cmds:
      - helm upgrade --install {{.RELEASE_NAME}} {{.CHART_DIR}}

  uninstall:
    desc: Uninstall the chart from the current Kubernetes cluster
    cmds:
      - helm uninstall {{.RELEASE_NAME}}

  ci:
    desc: Run full CI pipeline (lint + test)
    cmds:
      - task lint
      - task test

  help:
    cmds:
      - task --list
    silent: true
