apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.dnsPort }}
      targetPort: dns
      protocol: UDP
      name: dns
    - port: {{ .Values.service.dnsPort }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.service.dnsTlsPort }}
      targetPort: dns-tls
      protocol: TCP
      name: dns-tls
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
